# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
language:         en-us
title:            '2020 All-Stars'
tagline:          'fantasy baseball from the future'
description:      "A twisted journey into the heart of deep-league fantasy baseball."
url:              http://2020allstars.da3.net
podcastext:       '/podcast.xml'
podcastfeedurl:   http://feeds.feedburner.com/2020allstars
baseurl:          '/'
paginate:         10
itunes:
  keywords:         "2020,Allstars,MLB,Fantasy,Baseball,MILB,deep-league,keeper-league,NL-Only,AL-Only,closerpocalypse"
  category1:        'Sports & Recreation'
  category2:        ''
  category3:        ''
  image:            https://dl.dropboxusercontent.com/u/89720649/2020allstars.jpg
  limit:            1000
  url:              https://itunes.apple.com/us/podcast/2020-all-stars-podcast/id679001606
twitter:
  handle:         '@2020AllStars'
  url:            'https://twitter.com/2020allstars'
instagram:
  handle:         '2020AllStars'

author:
  name:           '2020 All-Stars'
  url:            https://twitter.com/2020allstars
  email:          '2020allstars@da3.net'
  crname:         'David Pollack and Todd Sakamoto'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/2020allstars/2020allstars.github.io