# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '2020 Allstars'
tagline:          'fantasy baseball from the future'
description:      'A twisted journey into the heart of fantasy baseball. We\'re staking our reputations to George Springer and Will Harris. That\'s all you need to know.'
url:              http://2020allstars.github.io
baseurl:          '/'
paginate:         10

author:
  name:           'David Pollack and Todd Sakamoto'
  url:            https://twitter.com/2020allstars

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/2020allstars/lanyon
